---
title: "git_01"
author: "Sarah Medina"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Five little girls of Five, Four, Three, Two, One:  
Rolling on the hearthrug, full of tricks and fun.  
Five rosy girls, in years from Ten to Six:  
Sitting down to lessons–no more time for tricks.  
Five growing girls, from Fifteen to Eleven:  



## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Something there is that doesn’t love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:  



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd,because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  



## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

How many slams in an old screen door?  
Depends how loud you shut it.  
How many slices in a bread?  
Depends how thin you cut it.  
How much good inside a day?  
Depends how good you live ’em.  
How much love inside a friend?  
Depends how much you give ’em.  




